[tool.poetry]
name = "oz-back-django"
version = "0.1.0"
description = "python django"
authors = ["900chan <forjung1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
